//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.authServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMessage", Namespace="http://schemas.datacontract.org/2004/07/AuthService")]
    [System.SerializableAttribute()]
    public partial class UserMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsClient.authServiceReference.ServiceMetadata MetadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsClient.authServiceReference.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsClient.authServiceReference.ServiceMetadata Metadata {
            get {
                return this.MetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetadataField, value) != true)) {
                    this.MetadataField = value;
                    this.RaisePropertyChanged("Metadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsClient.authServiceReference.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceMetadata", Namespace="http://schemas.datacontract.org/2004/07/AuthService")]
    [System.SerializableAttribute()]
    public partial class ServiceMetadata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AuthService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="authServiceReference.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/VerifyAcessToBD", ReplyAction="http://tempuri.org/IAuthService/VerifyAcessToBDResponse")]
        string VerifyAcessToBD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/VerifyAcessToBD", ReplyAction="http://tempuri.org/IAuthService/VerifyAcessToBDResponse")]
        System.Threading.Tasks.Task<string> VerifyAcessToBDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsers", ReplyAction="http://tempuri.org/IAuthService/GetUsersResponse")]
        WindowsClient.authServiceReference.UserMessage GetUsers(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsers", ReplyAction="http://tempuri.org/IAuthService/GetUsersResponse")]
        System.Threading.Tasks.Task<WindowsClient.authServiceReference.UserMessage> GetUsersAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUser", ReplyAction="http://tempuri.org/IAuthService/GetUserResponse")]
        WindowsClient.authServiceReference.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUser", ReplyAction="http://tempuri.org/IAuthService/GetUserResponse")]
        System.Threading.Tasks.Task<WindowsClient.authServiceReference.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/UpdateUserDescription", ReplyAction="http://tempuri.org/IAuthService/UpdateUserDescriptionResponse")]
        WindowsClient.authServiceReference.ServiceMetadata UpdateUserDescription(string login, string password, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/UpdateUserDescription", ReplyAction="http://tempuri.org/IAuthService/UpdateUserDescriptionResponse")]
        System.Threading.Tasks.Task<WindowsClient.authServiceReference.ServiceMetadata> UpdateUserDescriptionAsync(string login, string password, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/UpdateUserDescriptionByCertificate", ReplyAction="http://tempuri.org/IAuthService/UpdateUserDescriptionByCertificateResponse")]
        WindowsClient.authServiceReference.ServiceMetadata UpdateUserDescriptionByCertificate(string pcks7Base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/UpdateUserDescriptionByCertificate", ReplyAction="http://tempuri.org/IAuthService/UpdateUserDescriptionByCertificateResponse")]
        System.Threading.Tasks.Task<WindowsClient.authServiceReference.ServiceMetadata> UpdateUserDescriptionByCertificateAsync(string pcks7Base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetHashes", ReplyAction="http://tempuri.org/IAuthService/GetHashesResponse")]
        string[] GetHashes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetHashes", ReplyAction="http://tempuri.org/IAuthService/GetHashesResponse")]
        System.Threading.Tasks.Task<string[]> GetHashesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsersByCertificate", ReplyAction="http://tempuri.org/IAuthService/GetUsersByCertificateResponse")]
        WindowsClient.authServiceReference.UserMessage GetUsersByCertificate(string pkcsBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsersByCertificate", ReplyAction="http://tempuri.org/IAuthService/GetUsersByCertificateResponse")]
        System.Threading.Tasks.Task<WindowsClient.authServiceReference.UserMessage> GetUsersByCertificateAsync(string pkcsBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/UpdateUserPassword", ReplyAction="http://tempuri.org/IAuthService/UpdateUserPasswordResponse")]
        WindowsClient.authServiceReference.ServiceMetadata UpdateUserPassword(string pkcs7Base64, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/UpdateUserPassword", ReplyAction="http://tempuri.org/IAuthService/UpdateUserPasswordResponse")]
        System.Threading.Tasks.Task<WindowsClient.authServiceReference.ServiceMetadata> UpdateUserPasswordAsync(string pkcs7Base64, string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : WindowsClient.authServiceReference.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<WindowsClient.authServiceReference.IAuthService>, WindowsClient.authServiceReference.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VerifyAcessToBD() {
            return base.Channel.VerifyAcessToBD();
        }
        
        public System.Threading.Tasks.Task<string> VerifyAcessToBDAsync() {
            return base.Channel.VerifyAcessToBDAsync();
        }
        
        public WindowsClient.authServiceReference.UserMessage GetUsers(string login, string password) {
            return base.Channel.GetUsers(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.authServiceReference.UserMessage> GetUsersAsync(string login, string password) {
            return base.Channel.GetUsersAsync(login, password);
        }
        
        public WindowsClient.authServiceReference.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.authServiceReference.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public WindowsClient.authServiceReference.ServiceMetadata UpdateUserDescription(string login, string password, string description) {
            return base.Channel.UpdateUserDescription(login, password, description);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.authServiceReference.ServiceMetadata> UpdateUserDescriptionAsync(string login, string password, string description) {
            return base.Channel.UpdateUserDescriptionAsync(login, password, description);
        }
        
        public WindowsClient.authServiceReference.ServiceMetadata UpdateUserDescriptionByCertificate(string pcks7Base64) {
            return base.Channel.UpdateUserDescriptionByCertificate(pcks7Base64);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.authServiceReference.ServiceMetadata> UpdateUserDescriptionByCertificateAsync(string pcks7Base64) {
            return base.Channel.UpdateUserDescriptionByCertificateAsync(pcks7Base64);
        }
        
        public string[] GetHashes() {
            return base.Channel.GetHashes();
        }
        
        public System.Threading.Tasks.Task<string[]> GetHashesAsync() {
            return base.Channel.GetHashesAsync();
        }
        
        public WindowsClient.authServiceReference.UserMessage GetUsersByCertificate(string pkcsBase64) {
            return base.Channel.GetUsersByCertificate(pkcsBase64);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.authServiceReference.UserMessage> GetUsersByCertificateAsync(string pkcsBase64) {
            return base.Channel.GetUsersByCertificateAsync(pkcsBase64);
        }
        
        public WindowsClient.authServiceReference.ServiceMetadata UpdateUserPassword(string pkcs7Base64, string login) {
            return base.Channel.UpdateUserPassword(pkcs7Base64, login);
        }
        
        public System.Threading.Tasks.Task<WindowsClient.authServiceReference.ServiceMetadata> UpdateUserPasswordAsync(string pkcs7Base64, string login) {
            return base.Channel.UpdateUserPasswordAsync(pkcs7Base64, login);
        }
    }
}
